
// Nepal-specific exchange centers seed data
export const seedData = [
    {
        name: 'Devis Metro Money Exchange Pvt. Ltd',
        description: 'Leading currency exchange service in Kathmandu with competitive rates for all major currencies including USD, EUR, GBP, and more.',
        location: 'Kathmandu',
        address: 'Kathmandu 44600, Nepal',
        googleMapLink: 'https://maps.app.goo.gl/FnHjngiWc8yR3vWr5',
        rating: 4.8,
        services: ['Currency Exchange', 'Money Transfer', 'Western Union', 'IME', 'Travel Cards'],
        phone: '+977-015100931',
        hours: 'Sun-Fri: 9AM-6PM, Sat: 10AM-4PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 27.7172,
        lng: 85.3240,
        isActive: true
    },
    {
        name: 'Lp Money Exchange',
        description: 'Trusted money exchange service in the patan area, serving tourists and locals with excellent rates and quick service.',
        location: 'Patan,Lalitpur',
        address: 'M8GG+276, Kwalakhu Rd, Lalitpur 44600',
        googleMapLink: 'https://maps.app.goo.gl/4TE84L3K7UTDnPzU6',
        rating: 4.6,
        services: ['Currency Exchange', 'Travel Cards', 'Remittance', 'Money Transfer'],
        phone: '+977-9841304004',
        hours: 'Daily: 8AM-8PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 28.2096,
        lng: 83.9856,
        isActive: true
    },
    {
        name: 'Bhaktapur Money Exchange',
        description: 'Reliable exchange center in Bhaktapur area providing excellent service for currency exchange and remittance services.',
        location: 'Bhaktapur',
        address: 'MCCJ+H3J, Bhaktapur 44800, Nepal',
        googleMapLink: 'https://maps.app.goo.gl/k7xFfjsLJzRjmnYX9',
        rating: 4.5,
        services: ['Currency Exchange', 'Money Transfer', 'Remittance'],
        phone: '+977-016610499',
        hours: 'Sun-Fri: 9AM-5PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 27.6747,
        lng: 84.4240,
        isActive: true
    },
    {
        name: 'Annapurna Money Exchange',
        description: 'Modern exchange center in Butwal with digital services, competitive rates, and excellent customer service.',
        location: 'Thamel, Kathmandu',
        address: 'P866+XF7, Thamel Marg, Kathmandu 44600, Nepal',
        googleMapLink: 'https://maps.app.goo.gl/K21hmUCYSaWr63Pv8',
        rating: 4.7,
        services: ['Currency Exchange', 'Digital Payments', 'Mobile Banking', 'Money Transfer'],
        phone: '+977-014218091',
        hours: 'Sun-Fri: 9AM-6PM, Sat: 10AM-3PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 27.7000,
        lng: 83.4486,
        isActive: true
    },
    {
        name: 'Patan Money Exchange Pvt. Ltd.',
        description: 'A premier exchange center serving tourists and surrounding areas with reliable currency exchange services.',
        location: 'ManBhavana, Lalitpur',
        address: 'M8C8+QFH, मानभवन सडक, Lalitpur 44700, Nepal',
        googleMapLink: 'https://maps.app.goo.gl/ioPXcFN48epULJBU6',
        rating: 4.3,
        services: ['Currency Exchange', 'International Transfer', 'Forex Cards', 'Remittance'],
        phone: '+977-015542975',
        hours: 'Sun-Fri: 9AM-5PM, Sat: 9AM-2PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 26.8147,
        lng: 87.2847,
        isActive: true
    },
    {
        name: 'Bhaktapur Remit',
        description: 'Established exchange center in Bhaktapur with over 15 years of trusted service and competitive exchange rates.',
        location: 'Bhaktapur',
        address: 'MCCG+XW5, Bhaktapur 44800, Nepal',
        googleMapLink: 'https://maps.app.goo.gl/TUdZMfpXMtTWp27a9',
        rating: 4.4,
        services: ['Currency Exchange', 'Remittance', 'Money Transfer'],
        phone: '+977-016619152',
        hours: 'Sun-Fri: 9AM-6PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 26.4525,
        lng: 87.2718,
        isActive: true
    },
    {
        name: 'WESTERN UNION MONEY EXCHANGE',
        description: 'Premium exchange service located in Kathmandu\'s commercial hub with best rates and professional service.',
        location: 'Kathmandu',
        address: 'Inside Thamel Supermarket, Paryatan Marg, 44600 Kathmandu, Nepal',
        googleMapLink: 'https://maps.app.goo.gl/hchMZ9XPCaLoiqLP9',
        rating: 4.9,
        services: ['Currency Exchange', 'Corporate Services', 'Bulk Exchange', 'Investment Advisory'],
        phone: '+977-014700167',
        hours: 'Sun-Fri: 8.30AM-8.30PM, Sat: 9AM-4PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 27.7024,
        lng: 85.3146,
        isActive: true
    },
    {
        name: 'Dangol International Pvt Ltd',
        description: 'Local exchange center in Lalitpur providing personalized service to the community with competitive rates.',
        location: 'Lalitpur',
        address: 'Lalitpur, Near Samjhana Beauty Parlour, Bus Park, 44700',
        googleMapLink: 'https://maps.app.goo.gl/ntFeRfApcG1uUPBZ7',
        rating: 4.2,
        services: ['Currency Exchange', 'Local Transfer', 'Savings', 'Money Transfer'],
        phone: '+977-014004642',
        hours: 'Sun-Fri: 9AM-4PM',
        images: ["himalayan-exchange-1.jpg", "himalayan-exchange-2.jpg"],
        lat: 26.6667,
        lng: 87.7000,
        isActive: true
    }
];
